#include "x264.h"
#include "common/log.h"

void dfx_x264_param(x264_param_t* param)
{
    log_debug("----------threads-----------");
    log_debug("CPU flags: %u", param->cpu);
    log_debug("i_threads: %d", param->i_threads);
    log_debug("i_lookahead_threads: %d", param->i_lookahead_threads);
    log_debug("b_sliced_threads: %d", param->b_sliced_threads);
    log_debug("b_deterministic: %d", param->b_deterministic);
    log_debug("b_cpu_independent: %d", param->b_cpu_independent);
    log_debug("i_sync_lookahead: %d", param->i_sync_lookahead);
    log_debug("----------basic-------------");
    log_debug("i_width: %d", param->i_width);
    log_debug("i_height: %d", param->i_height);
    log_debug("i_csp: %d", param->i_csp);
    log_debug("i_bitdepth: %d", param->i_bitdepth);
    log_debug("i_level_idc: %d", param->i_level_idc);
    log_debug("i_frame_total: %d", param->i_frame_total);
    log_debug("i_nal_hrd: %d", param->i_nal_hrd);
    log_debug("-----------vui--------------");
    log_debug("vui.i_sar_height: %d", param->vui.i_sar_height);
    log_debug("vui.i_sar_width: %d", param->vui.i_sar_width);
    log_debug("vui.i_overscan: %d", param->vui.i_overscan);
    log_debug("vui.i_vidformat: %d", param->vui.i_vidformat);
    log_debug("vui.b_fullrange: %d", param->vui.b_fullrange);
    log_debug("vui.i_colorprim: %d", param->vui.i_colorprim);
    log_debug("vui.i_transfer: %d", param->vui.i_transfer);
    log_debug("vui.i_colmatrix: %d", param->vui.i_colmatrix);
    log_debug("vui.i_chroma_loc: %d", param->vui.i_chroma_loc);
    log_debug("-----------frame-structure--------------");
    log_debug("i_frame_reference: %d", param->i_frame_reference);
    log_debug("i_dpb_size: %d", param->i_dpb_size);
    log_debug("i_keyint_max: %d", param->i_keyint_max);
    log_debug("i_keyint_min: %d", param->i_keyint_min);
    log_debug("i_scenecut_threshold: %d", param->i_scenecut_threshold);
    log_debug("b_intra_refresh: %d", param->b_intra_refresh);
    log_debug("i_bframe: %d", param->i_bframe);
    log_debug("i_bframe_adaptive: %d", param->i_bframe_adaptive);
    log_debug("i_bframe_bias: %d", param->i_bframe_bias);
    log_debug("i_bframe_pyramid: %d", param->i_bframe_pyramid);
    log_debug("b_open_gop: %d", param->b_open_gop);
    log_debug("b_bluray_compat: %d", param->b_bluray_compat);
    log_debug("i_avcintra_class: %d", param->i_avcintra_class);
    log_debug("i_avcintra_flavor: %d", param->i_avcintra_flavor);
    log_debug("b_deblocking_filter: %d", param->b_deblocking_filter);
    log_debug("i_deblocking_filter_alphac0: %d", param->i_deblocking_filter_alphac0);
    log_debug("i_deblocking_filter_beta: %d", param->i_deblocking_filter_beta);
    log_debug("b_cabac: %d", param->b_cabac);
    log_debug("i_cabac_init_idc: %d", param->i_cabac_init_idc);
    log_debug("b_interlaced: %d", param->b_interlaced);
    log_debug("b_constrained_intra: %d", param->b_constrained_intra);
    log_debug("i_cqm_preset: %d", param->i_cqm_preset);
    log_debug("i_log_level: %d", param->i_log_level);
    log_debug("b_full_recon: %d", param->b_full_recon);
    log_debug("----------analysis-------------");
    log_debug("analyse.intra: %u", param->analyse.intra);
    log_debug("analyse.inter: %u", param->analyse.inter);
    log_debug("analyse.b_transform_8x8: %d", param->analyse.b_transform_8x8);
    log_debug("analyse.i_weighted_pred: %d", param->analyse.i_weighted_pred);
    log_debug("analyse.b_weighted_bipred: %d", param->analyse.b_weighted_bipred);
    log_debug("analyse.i_direct_mv_pred: %d", param->analyse.i_direct_mv_pred);
    log_debug("analyse.i_chroma_qp_offset: %d", param->analyse.i_chroma_qp_offset);
    log_debug("analyse.i_me_method: %d", param->analyse.i_me_method);
    log_debug("analyse.i_me_range: %d", param->analyse.i_me_range);
    log_debug("analyse.i_mv_range: %d", param->analyse.i_mv_range);
    log_debug("analyse.i_mv_range_thread: %d", param->analyse.i_mv_range_thread);
    log_debug("analyse.i_subpel_refine: %d", param->analyse.i_subpel_refine);
    log_debug("analyse.b_chroma_me: %d", param->analyse.b_chroma_me);
    log_debug("analyse.b_mixed_references: %d", param->analyse.b_mixed_references);
    log_debug("analyse.i_trellis: %d", param->analyse.i_trellis);
    log_debug("analyse.b_fast_pskip: %d", param->analyse.b_fast_pskip);
    log_debug("analyse.b_dct_decimate: %d", param->analyse.b_dct_decimate);
    log_debug("analyse.i_noise_reduction: %d", param->analyse.i_noise_reduction);
    log_debug("analyse.f_psy_rd: %f", param->analyse.f_psy_rd);
    log_debug("analyse.f_psy_trellis: %f", param->analyse.f_psy_trellis);
    log_debug("analyse.b_psy: %d", param->analyse.b_psy);
    log_debug("analyse.b_mb_info: %d", param->analyse.b_mb_info);
    log_debug("analyse.b_mb_info_update: %d", param->analyse.b_mb_info_update);
    log_debug("analyse.i_luma_deadzone[0]: %d", param->analyse.i_luma_deadzone[0]);
    log_debug("analyse.i_luma_deadzone[1]: %d", param->analyse.i_luma_deadzone[1]);
    log_debug("analyse.b_psnr: %d", param->analyse.b_psnr);
    log_debug("analyse.b_ssim: %d", param->analyse.b_ssim);
    log_debug("----------rate-control-------------");
    log_debug("rc.i_rc_method: %d", param->rc.i_rc_method);
    log_debug("rc.i_qp_constant: %d", param->rc.i_qp_constant);
    log_debug("rc.i_qp_min: %d", param->rc.i_qp_min);
    log_debug("rc.i_qp_max: %d", param->rc.i_qp_max);
    log_debug("rc.i_qp_step: %d", param->rc.i_qp_step);
    log_debug("rc.i_bitrate: %d", param->rc.i_bitrate);
    log_debug("rc.f_rf_constant: %f", param->rc.f_rf_constant);
    log_debug("rc.f_rf_constant_max: %f", param->rc.f_rf_constant_max);
    log_debug("rc.f_rate_tolerance: %f", param->rc.f_rate_tolerance);
    log_debug("rc.i_vbv_max_bitrate: %d", param->rc.i_vbv_max_bitrate);
    log_debug("rc.i_vbv_buffer_size: %d", param->rc.i_vbv_buffer_size);
    log_debug("rc.f_vbv_buffer_init: %f", param->rc.f_vbv_buffer_init);
    log_debug("rc.f_ip_factor: %f", param->rc.f_ip_factor);
    log_debug("rc.f_pb_factor: %f", param->rc.f_pb_factor);
    log_debug("rc.b_filler: %d", param->rc.b_filler);
    log_debug("rc.i_aq_mode: %d", param->rc.i_aq_mode);
    log_debug("rc.f_aq_strength: %f", param->rc.f_aq_strength);
    log_debug("rc.b_mb_tree: %d", param->rc.b_mb_tree);
    log_debug("rc.i_lookahead: %d", param->rc.i_lookahead);
    log_debug("rc.b_stat_write: %d", param->rc.b_stat_write);
    log_debug("rc.b_stat_read: %d", param->rc.b_stat_read);
    log_debug("rc.f_qcompress: %f", param->rc.f_qcompress);
    log_debug("rc.f_qblur: %f", param->rc.f_qblur);
    log_debug("rc.f_complexity_blur: %f", param->rc.f_complexity_blur);
    log_debug("rc.i_zones: %d", param->rc.i_zones);
    log_debug("-------------others--------------");
    log_debug("i_alternative_transfer: %d", param->i_alternative_transfer);
    log_debug("b_aud: %d", param->b_aud);
    log_debug("b_repeat_headers: %d", param->b_repeat_headers);
    log_debug("b_annexb: %d", param->b_annexb);
    log_debug("i_sps_id: %d", param->i_sps_id);
    log_debug("b_vfr_input: %d", param->b_vfr_input);
    log_debug("b_pulldown: %d", param->b_pulldown);
    log_debug("i_fps_num: %u", param->i_fps_num);
    log_debug("i_fps_den: %u", param->i_fps_den);
    log_debug("i_timebase_num: %u", param->i_timebase_num);
    log_debug("i_timebase_den: %u", param->i_timebase_den);
    log_debug("b_tff: %d", param->b_tff);
    log_debug("b_pic_struct: %d", param->b_pic_struct);
    log_debug("b_fake_interlaced: %d", param->b_fake_interlaced);
    log_debug("b_stitchable: %d", param->b_stitchable);
    log_debug("i_slice_max_size: %d", param->i_slice_max_size);
    log_debug("i_slice_max_mbs: %d", param->i_slice_max_mbs);
    log_debug("i_slice_min_mbs: %d", param->i_slice_min_mbs);
    log_debug("i_slice_count: %d", param->i_slice_count);
    log_debug("i_slice_count_max: %d", param->i_slice_count_max);
}