# External Libraries Detection and Configuration
# This module detects optional external libraries for x264 CLI

# Initialize optional library variables
find_package(PkgConfig QUIET)

set(HAVE_AVS 0)
set(HAVE_SWSCALE 0)
set(HAVE_LAVF 0)
set(HAVE_FFMS 0)
set(HAVE_GPAC 0)
set(HAVE_LSMASH 0)

set(X264CLI_OPTIONAL_LIBS)
set(X264CLI_OPTIONAL_INCLUDE_DIRS)
set(X264CLI_OPTIONAL_COMPILE_OPTIONS)

# Avisynth (runtime loaded)
if(ENABLE_AVS STREQUAL "off")
    message(STATUS "Avisynth support disabled by user")
else()
    if(SYS_WINDOWS OR SYS_LINUX OR SYS_MACOSX)
        set(HAVE_AVS 1)
        if(SYS_LINUX)
            list(APPEND X264CLI_OPTIONAL_LIBS dl)
        endif()
        message(STATUS "Avisynth support enabled")
    elseif(ENABLE_AVS STREQUAL "on")
        message(FATAL_ERROR "Avisynth support requested but unsupported on this platform")
    else()
        message(STATUS "Avisynth not supported on this platform; disabling")
    endif()
endif()

# libswscale
if(ENABLE_SWSCALE STREQUAL "off")
    message(STATUS "libswscale support disabled by user")
else()
    set(_swscale_libs)
    set(_swscale_includes)
    set(_swscale_cflags)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(PC_SWSCALE QUIET libswscale libavutil)
        if(PC_SWSCALE_FOUND)
            set(_swscale_libs ${PC_SWSCALE_LIBRARIES})
            set(_swscale_includes ${PC_SWSCALE_INCLUDE_DIRS})
            set(_swscale_cflags ${PC_SWSCALE_CFLAGS_OTHER})
        endif()
    endif()
    if(NOT _swscale_libs)
        find_path(SWSCALE_INCLUDE_DIR libswscale/swscale.h)
        find_library(SWSCALE_LIBRARY NAMES swscale)
        find_library(AVUTIL_LIBRARY NAMES avutil)
        if(SWSCALE_INCLUDE_DIR AND SWSCALE_LIBRARY AND AVUTIL_LIBRARY)
            set(_swscale_libs ${SWSCALE_LIBRARY} ${AVUTIL_LIBRARY})
            set(_swscale_includes ${SWSCALE_INCLUDE_DIR})
        endif()
    endif()
    if(_swscale_libs)
        set(HAVE_SWSCALE 1)
        list(APPEND X264CLI_OPTIONAL_LIBS ${_swscale_libs})
        list(APPEND X264CLI_OPTIONAL_INCLUDE_DIRS ${_swscale_includes})
        list(APPEND X264CLI_OPTIONAL_COMPILE_OPTIONS ${_swscale_cflags})
        message(STATUS "libswscale support enabled")
    elseif(ENABLE_SWSCALE STREQUAL "on")
        message(FATAL_ERROR "libswscale support requested but not found")
    else()
        message(STATUS "libswscale not found; disabling support")
    endif()
endif()

# libavformat (requires libswscale)
if(ENABLE_LAVF STREQUAL "off")
    message(STATUS "libavformat support disabled by user")
elseif(NOT HAVE_SWSCALE)
    if(ENABLE_LAVF STREQUAL "on")
        message(FATAL_ERROR "libavformat support requested but libswscale is unavailable")
    else()
        message(STATUS "libavformat disabled because libswscale support is missing")
    endif()
else()
    set(_lavf_libs)
    set(_lavf_includes)
    set(_lavf_cflags)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(PC_LAVF QUIET libavformat libavcodec libavutil)
        if(PC_LAVF_FOUND)
            set(_lavf_libs ${PC_LAVF_LIBRARIES})
            set(_lavf_includes ${PC_LAVF_INCLUDE_DIRS})
            set(_lavf_cflags ${PC_LAVF_CFLAGS_OTHER})
        endif()
    endif()
    if(NOT _lavf_libs)
        find_library(LAVFORMAT_LIBRARY NAMES avformat)
        find_library(LAVCODEC_LIBRARY NAMES avcodec)
        find_library(LAVUTIL_LIBRARY NAMES avutil)
        if(LAVFORMAT_LIBRARY AND LAVCODEC_LIBRARY AND LAVUTIL_LIBRARY)
            set(_lavf_libs ${LAVFORMAT_LIBRARY} ${LAVCODEC_LIBRARY} ${LAVUTIL_LIBRARY})
        endif()
    endif()
    if(_lavf_libs)
        set(HAVE_LAVF 1)
        list(APPEND X264CLI_OPTIONAL_LIBS ${_lavf_libs})
        list(APPEND X264CLI_OPTIONAL_INCLUDE_DIRS ${_lavf_includes})
        list(APPEND X264CLI_OPTIONAL_COMPILE_OPTIONS ${_lavf_cflags})
        message(STATUS "libavformat support enabled")
    elseif(ENABLE_LAVF STREQUAL "on")
        message(FATAL_ERROR "libavformat support requested but not found")
    else()
        message(STATUS "libavformat not found; disabling support")
    endif()
endif()

# ffms2 (requires libswscale)
if(ENABLE_FFMS STREQUAL "off")
    message(STATUS "ffms2 support disabled by user")
elseif(NOT HAVE_SWSCALE)
    if(ENABLE_FFMS STREQUAL "on")
        message(FATAL_ERROR "ffms2 support requested but libswscale is unavailable")
    else()
        message(STATUS "ffms2 disabled because libswscale support is missing")
    endif()
else()
    set(_ffms_libs)
    set(_ffms_includes)
    set(_ffms_cflags)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(PC_FFMS QUIET ffms2)
        if(PC_FFMS_FOUND)
            set(_ffms_libs ${PC_FFMS_LIBRARIES})
            set(_ffms_includes ${PC_FFMS_INCLUDE_DIRS})
            set(_ffms_cflags ${PC_FFMS_CFLAGS_OTHER})
        endif()
    endif()
    if(NOT _ffms_libs)
        find_library(FFMS_LIBRARY NAMES ffms2)
        if(FFMS_LIBRARY)
            set(_ffms_libs ${FFMS_LIBRARY})
        endif()
    endif()
    if(_ffms_libs)
        set(HAVE_FFMS 1)
        list(APPEND X264CLI_OPTIONAL_LIBS ${_ffms_libs})
        list(APPEND X264CLI_OPTIONAL_INCLUDE_DIRS ${_ffms_includes})
        list(APPEND X264CLI_OPTIONAL_COMPILE_OPTIONS ${_ffms_cflags})
        message(STATUS "ffms2 support enabled")
    elseif(ENABLE_FFMS STREQUAL "on")
        message(FATAL_ERROR "ffms2 support requested but not found")
    else()
        message(STATUS "ffms2 not found; disabling support")
    endif()
endif()

# L-SMASH
if(ENABLE_LSMASH STREQUAL "off")
    message(STATUS "L-SMASH support disabled by user")
else()
    set(_lsmash_libs)
    set(_lsmash_includes)
    set(_lsmash_cflags)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(PC_LSMASH QUIET liblsmash)
        if(PC_LSMASH_FOUND)
            set(_lsmash_libs ${PC_LSMASH_LIBRARIES})
            set(_lsmash_includes ${PC_LSMASH_INCLUDE_DIRS})
            set(_lsmash_cflags ${PC_LSMASH_CFLAGS_OTHER})
        endif()
    endif()
    if(NOT _lsmash_libs)
        find_library(LSMASH_LIBRARY NAMES lsmash)
        find_path(LSMASH_INCLUDE_DIR lsmash.h)
        if(LSMASH_LIBRARY AND LSMASH_INCLUDE_DIR)
            set(_lsmash_libs ${LSMASH_LIBRARY})
            set(_lsmash_includes ${LSMASH_INCLUDE_DIR})
        endif()
    endif()
    if(_lsmash_libs)
        set(HAVE_LSMASH 1)
        list(APPEND X264CLI_OPTIONAL_LIBS ${_lsmash_libs})
        list(APPEND X264CLI_OPTIONAL_INCLUDE_DIRS ${_lsmash_includes})
        list(APPEND X264CLI_OPTIONAL_COMPILE_OPTIONS ${_lsmash_cflags})
        message(STATUS "L-SMASH support enabled")
    elseif(ENABLE_LSMASH STREQUAL "on")
        message(FATAL_ERROR "L-SMASH support requested but not found")
    else()
        message(STATUS "L-SMASH not found; disabling support")
    endif()
endif()

# GPAC (skip if L-SMASH already enabled)
if(ENABLE_GPAC STREQUAL "off")
    message(STATUS "GPAC support disabled by user")
elseif(HAVE_LSMASH)
    message(STATUS "GPAC support skipped because L-SMASH is enabled")
else()
    set(_gpac_libs)
    set(_gpac_includes)
    set(_gpac_cflags)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(PC_GPAC QUIET gpac)
        if(PC_GPAC_FOUND)
            set(_gpac_libs ${PC_GPAC_LIBRARIES})
            set(_gpac_includes ${PC_GPAC_INCLUDE_DIRS})
            set(_gpac_cflags ${PC_GPAC_CFLAGS_OTHER})
        endif()
    endif()
    if(NOT _gpac_libs)
        find_library(GPAC_LIBRARY NAMES gpac gpac_static)
        if(GPAC_LIBRARY)
            set(_gpac_libs ${GPAC_LIBRARY})
        endif()
    endif()
    if(_gpac_libs)
        set(HAVE_GPAC 1)
        list(APPEND X264CLI_OPTIONAL_LIBS ${_gpac_libs})
        list(APPEND X264CLI_OPTIONAL_INCLUDE_DIRS ${_gpac_includes})
        list(APPEND X264CLI_OPTIONAL_COMPILE_OPTIONS ${_gpac_cflags})
        message(STATUS "GPAC support enabled")
    elseif(ENABLE_GPAC STREQUAL "on")
        message(FATAL_ERROR "GPAC support requested but not found")
    else()
        message(STATUS "GPAC not found; disabling support")
    endif()
endif()

# Remove duplicates if lists are not empty
if(X264CLI_OPTIONAL_LIBS)
    list(REMOVE_DUPLICATES X264CLI_OPTIONAL_LIBS)
endif()
if(X264CLI_OPTIONAL_INCLUDE_DIRS)
    list(REMOVE_DUPLICATES X264CLI_OPTIONAL_INCLUDE_DIRS)
endif()
if(X264CLI_OPTIONAL_COMPILE_OPTIONS)
    list(REMOVE_DUPLICATES X264CLI_OPTIONAL_COMPILE_OPTIONS)
endif()
